name: met
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  firebase_storage: ^3.1.6
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  modal_progress_hud: ^0.1.3
  file_picker: ^1.12.0
  status_alert: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/